### ISSUE TITLE
Doesn't always block JS

### ISSUE THREAD

**Issue by RegretfulCarrot** [idlewan/javascript-control#5]
Oftentimes a page opened runs javascript and this extension can do nothing about it.
The extension works better on Android than on Ubuntu as it blocks JS way better.

**Comment by PatrickSocha** [comment]
Bump. I have also noticed the same. See the following, running latest Firefox: https://www.enable-javascript.com/.

**Comment by tichun** [comment]
But on Android it sometimes acts the other way around - it will block JS even after clicking on the icon.
